quarkus:
  jackson:
    property-naming-strategy: SNAKE_CASE
  http:
    auth:
      basic: true
      policy:
        admin-policy:
          roles-allowed: admin
      permission:
        open-permission:
          policy: permit
          methods: GET,OPTIONS
          paths: /*
          enabled: true
        admin-permission:
          policy: admin-policy
          paths: /*
          methods: POST,PUT,PATCH,DELETE
    cors:
      ~: true
      origins: http://localhost:4200,https://live.dev.bitwars.online,https://live.bitwars.online,https://bitdealer.bitwars.online,https://bitdealer.dev.bitwars.online
      headers: accept, authorization, content-type, x-requested-with
      methods: GET,OPTIONS,POST,PUT,PATCH,DELETE
      exposed-headers: "location,info"
      access-control-max-age: 24H
      allow-credentials: true
      # For Test:
      # curl -H "Origin: https://live.dev.bitwars.online" --verbose http://localhost:8080/games
      # check response for access-control-allow-credentials

  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          admin: ${API_PASSWORD:admin}
        roles:
          admin: admin



  swagger-ui:
    always-include: true


  datasource:
    db-kind: h2
    jdbc:
      url: "jdbc:h2:/home/jboss/persistence/gamedb"
  hibernate-orm:
    database:
      generation: update

  kubernetes:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    strategy: recreate
    security-context:
      run-as-user: 185
      run-as-group: 185
      fs-group: 185

    mounts:
      gamestore:
        path: /home/jboss/persistence
    pvc-volumes:
      gamestore:
        claim-name: pvc-dealer-gamestore
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 3500m
        memory: 6Gi
    env:
      mapping:
        "api_password":
          from-secret: api-user
          with-key: password
      secrets: api-user
  log:
    level: INFO
    category:
      "de.bitwars":
        level: INFO
      "de.bitwars.live":
        level: INFO
      "de.bitwars.api.resources":
        level: INFO

game:
  executor:
    poolsize: 10

"%dev":
  quarkus:
    #    hibernate-orm:
    #      database:
    #        generation: drop-and-create
    datasource:
      jdbc:
        url: "jdbc:h2:./gamedb"
    log:
      level: INFO
      category:
        "de.bitwars":
          level: INFO

"%test":
  quarkus:
    datasource:
      jdbc:
        url: "jdbc:h2:mem:gamedb"
